/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "stm32f407xx.h"
#include "stm32f4xx_gpio_driver.h"
#include "stm32f407xx_usart_driver.h"
#include <lcd.h>

char msg[1024] = "SNAP\n";

USART_Handle_t USART6_handle;

// --- Global Flags and Data ---
volatile uint8_t sensor_trigger = 0; // Set in ISR, read in main
volatile const char password[] = "5647";
volatile const char key_map[4][4] = {
    {'1', '2', '3', 'A'},
    {'4', '5', '6', 'B'},
    {'7', '8', '9', 'C'},
    {'*', '0', '#', 'D'}
};

// --- Prototypes ---
void delay(void);
void mdelay(uint32_t cnt);
void GPIO_KeypadInit(void);
void GPIO_IIRInit(void);
void Run_Password_Entry(void);
void USART6_GPIOInit(void);
void USART6_Init(void);

// --- Delay Functions ---
void mdelay(uint32_t cnt) {
    for(uint32_t i=0 ; i < (cnt * 1000); i++);
}

void delay(void) {
    for(uint32_t i = 0; i < 300000; i++);
}

// --- Initialization Functions ---
void GPIO_KeypadInit() {
    GPIO_Handle_t GPIO_key;
    memset(&GPIO_key, 0, sizeof(GPIO_key));

    // Rows (PD0-PD3) as Output
    GPIO_key.pGPIOx = GPIOD;
    GPIO_key.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    GPIO_key.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GPIO_key.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

    for(int i = 0; i <= 3; i++) {
        GPIO_key.GPIO_PinConfig.GPIO_PinNumber = i+11;
        GPIO_Init(&GPIO_key);
        GPIO_WriteToOutputPin(GPIOD, i+11, 1); // Default Rows HIGH
    }

    // Columns (PA0-PA3) as Input with Pull-Up
    GPIO_key.pGPIOx = GPIOA;
    GPIO_key.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
    GPIO_key.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;

    for(int i = 0; i <= 3; i++) {
        GPIO_key.GPIO_PinConfig.GPIO_PinNumber = i;
        GPIO_Init(&GPIO_key);
    }
}

void GPIO_IIRInit() {
    GPIO_Handle_t IIR_Handle;
    memset(&IIR_Handle, 0, sizeof(IIR_Handle));

    IIR_Handle.pGPIOx = GPIOB;
    IIR_Handle.GPIO_PinConfig.GPIO_PinNumber = 0;
    IIR_Handle.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN; // Falling edge trigger
    IIR_Handle.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    IIR_Handle.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

    GPIO_Init(&IIR_Handle);

}

void USART6_GPIOInit(void) {
    GPIO_Handle_t usart_gpios;
    memset(&usart_gpios, 0, sizeof(usart_gpios));

    // CORRECTED: USART6 is on GPIOC (Pins 6 and 7) for AF8
    usart_gpios.pGPIOx = GPIOC;
    usart_gpios.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    usart_gpios.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    usart_gpios.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;
    usart_gpios.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    usart_gpios.GPIO_PinConfig.GPIO_PinAltFunMode = 8; // AF8 for USART6

    // USART6 TX (PC6)
    usart_gpios.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_6;
    GPIO_Init(&usart_gpios);

    // USART6 RX (PC7)
    usart_gpios.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_7;
    GPIO_Init(&usart_gpios);
}

void USART6_Init(void) {
    USART6_handle.pUSARTx = USART6;
    USART6_handle.USART_Config.USART_Baud = USART_STD_BAUD_9600;
    USART6_handle.USART_Config.USART_HWFlowControl = USART_HW_FLOW_CTRL_NONE;
    USART6_handle.USART_Config.USART_Mode = USART_MODE_ONLY_TX;
    USART6_handle.USART_Config.USART_NoOfStopBits = USART_STOPBITS_1;
    USART6_handle.USART_Config.USART_WordLength = USART_WORDLEN_8BITS;
    USART6_handle.USART_Config.USART_ParityControl = USART_PARITY_DISABLE;
    USART_Init(&USART6_handle);
}

// --- Application Logic ---
void Run_Password_Entry(void) {
    GPIO_KeypadInit();
    char temppw[5] = {0};
    uint8_t count = 0;

    lcd_display_clear();
    lcd_print_string("Sensor Triggered!");
    mdelay(1000);
    lcd_display_clear();
    lcd_print_string("Enter Password:");
    while(count < 4) {
            for(uint8_t row = 0; row < 4; row++) {

                // FIX: Add + 11 to match your initialization
                GPIO_WriteToOutputPin(GPIOD, row + 11, 0); // Pull Row LOW

                for(uint8_t col = 0; col < 4; col++) {
                    if(GPIO_ReadFromInputPin(GPIOA, col) == 0) {
                        delay(); // Debounce
                        if(GPIO_ReadFromInputPin(GPIOA, col) == 0) {
                            temppw[count] = key_map[row][col];
                            lcd_print_string("*");
                            count++;

                            printf("Key: %c\n", key_map[row][col]);

                            while(GPIO_ReadFromInputPin(GPIOA, col) == 0); // Release
                        }
                    }
                }
                // FIX: Add + 11 to match your initialization
                GPIO_WriteToOutputPin(GPIOD, row + 11, 1); // Row back to HIGH

                if(count >= 4) break;
            }
        }
    if(strcmp((char*)temppw, (char*)password) == 0) {
        lcd_display_clear();
        printf("enterd");
        lcd_print_string("<SUCCESS>");
        mdelay(1000);
        lcd_display_clear();
        lcd_print_string("Identity Verified");

        // Evaporate hardware
        GPIO_DeInit(GPIOA);
        GPIO_DeInit(GPIOD);

    } else {
        lcd_display_clear();
        printf("photo");
        lcd_print_string("<DENIED>");
        mdelay(1000);
        lcd_display_clear();
        lcd_print_string("Security Breach!");
        mdelay(1000);

        // 1. Initialize USART6 Hardware
        USART6_GPIOInit();
        USART6_Init();

        // 2. Enable Peripheral
        USART_PeripheralControl(USART6, ENABLE);

        // 3. Transmit the Trigger Message
        // Ensure you have a USART_SendData function in your driver.
        USART_SendData(&USART6_handle, (uint8_t*)msg, strlen(msg));

        // Wait a brief moment to ensure transmission completes before de-init
        mdelay(100);

        // 4. Clean up
        USART_PeripheralControl(USART6, DISABLE);

        lcd_display_clear();
        lcd_print_string("PHOTO SENT");

        // Evaporate hardware
        GPIO_DeInit(GPIOA);
        GPIO_DeInit(GPIOD);
    }
}

// --- Interrupt Handler ---

// --- Main execution ---
int main(void) {
    GPIO_IIRInit();
    lcd_init();
    lcd_display_clear();

    printf("1\n");
    lcd_print_string("System Online");
    //printf("Security System Online. Monitoring IR Sensor (PB0)...\n");

    while(1) {
        // If the sensor was triggered via interrupt
        if(!GPIO_ReadFromInputPin(GPIOB,0)) {
            lcd_display_clear();
            lcd_print_string("Hello Sir");
            mdelay(1000);
            printf("2/n");

            Run_Password_Entry();
            sensor_trigger = 0; // Clear flag after handling

            // Re-prompt monitoring state
            mdelay(2000);
            lcd_display_clear();
            lcd_print_string("System Online");
        }
    }
}
